// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY_m-uEIUyXKSBHp2uKc_xcA9Afb0LYeU',
    appId: '1:1045982233358:web:e8001449f60ba200328d5f',
    messagingSenderId: '1045982233358',
    projectId: 'traveloi-bb757',
    authDomain: 'traveloi-bb757.firebaseapp.com',
    storageBucket: 'traveloi-bb757.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_uaRVU5kWl1cSDl6UVsV0nVfOh1Vq5ig',
    appId: '1:1045982233358:android:d05896cf32b7407d328d5f',
    messagingSenderId: '1045982233358',
    projectId: 'traveloi-bb757',
    storageBucket: 'traveloi-bb757.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsPsOHeXf85ljpfyg-u0df2e80u0yamIk',
    appId: '1:1045982233358:ios:a592c5cc22361aa8328d5f',
    messagingSenderId: '1045982233358',
    projectId: 'traveloi-bb757',
    storageBucket: 'traveloi-bb757.appspot.com',
    iosBundleId: 'com.example.traveloi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsPsOHeXf85ljpfyg-u0df2e80u0yamIk',
    appId: '1:1045982233358:ios:d33c11be039a5574328d5f',
    messagingSenderId: '1045982233358',
    projectId: 'traveloi-bb757',
    storageBucket: 'traveloi-bb757.appspot.com',
    iosBundleId: 'com.example.traveloi.RunnerTests',
  );
}
